---
- name: Deploy my app with Docker
  hosts: my_servers
  become: yes
  become_method: sudo
  tasks:
    - name: Update apt cache and install dependencies
      apt:
        update_cache: yes
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Check if the project directory exists
      stat:
        path: /home/saif/test
      register: project_directory

    - name: Clone the project repository (if not already cloned)
      git:
        repo: 'https://github.com/Saif-hadd/test.git'
        dest: /home/saif/test
        version: main
      when: not project_directory.stat.exists

    - name: Build and start the application with Docker Compose
      command: docker-compose -f /home/saif/test/docker-compose.yml -f /home/saif/test/docker-compose-front.yml -f /home/saif/test/docker-compose-back.yml up --build -d
      args:
        chdir: /home/saif/test

    - name: Verify if the containers are running
      command: docker ps
      register: docker_ps_output

    - name: Show docker ps output
      debug:
        var: docker_ps_output.stdout

