name: Deploy Application with Ansible

on:
  push:
    branches:
      - main  # Ou la branche de ton choix
  pull_request:
    branches:
      - main  # Ou la branche de ton choix

jobs:
  deploy:
    runs-on: ubuntu-latest  # Tu peux choisir une autre image si tu veux

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install ansible

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Set up SSH keys
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 196.239.8.207 >> ~/.ssh/known_hosts  # Ajoute ton IP publique ici

    - name: Clean up Docker
      run: |
        sudo apt-get remove -y docker docker-engine docker.io containerd runc
        sudo apt-get autoremove -y
        sudo apt-get update

    - name: Install Docker
      run: |
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg
        echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    - name: Run Ansible playbook
      run: |
        ansible-playbook -i inventory.ini deploy_app.yml --extra-vars "ansible_become_pass=saif"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
